# Generated by Django 4.1.4 on 2022-12-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_category_alter_job_job_type_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='job/'),
            preserve_default=False,
        ),
    ]
