# Generated by Django 3.2.5 on 2022-12-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='webiste',
            new_name='website',
        ),
    ]
